### ISSUE TITLE
Powermail form sending even if the reCaptcha is not checked

### ISSUE THREAD

**Issue by lmaranzano** [TehTux/jh_captcha#14]
I have problems with jh captcha on typo3 8.7.28 and 9.5.8 / powermail 7.3.1 / jh_captcha 3.0.1

When I fill a form, I can send it even if the captcha is not checked / validated. Have you ever had this problem and have a solution ?

Thank you in advance

**Comment by TehTux** [comment]
I will check this and give you a feedback. Thanks for your Issue!

**Comment by TehTux** [comment]
Sorry, i can't reproduce your problem. Maybe a missing config. Is the spamshield option in powermail enabled?

**Comment by schuberttobias** [comment]
I have the same problem: The reCAPTCHA v2 is rendered and usable, but I can send the form even if the captcha is not solved.

Yes, spamshield is enabled, because TypoScript/setup.txt of jh_captcha enables it with `_enable = 1`.

The exact same behavior occurs with [powermailrecaptcha](https://extensions.typo3.org/extension/powermailrecaptcha/).

Used versions:
- powermail 7.4.0 
- PHP: v7.2.24-0ubuntu0.18.04.6 
- TYPO3: 9.5.19
- jh_captcha: 3.0.3

Do you have any further ideas?

Thank you.

**Comment by schuberttobias** [comment]
P.S. I followed the [user manual](https://docs.typo3.org/p/haffner/jh_captcha/3.0/en-us/User/Index.html#), set version = 2, left out the v3 block and skipped the Optional Configuration.

**Comment by Voronov** [comment]
Check the documentation you have to provide some TypoScript
https://docs.typo3.org/p/haffner/jh_captcha/master/en-us/User/Index.html#typoscript
I think it should be 
`plugin.tx_powermail.settings.setup {
    validators.jh_captcha_recaptcha {
        class = \Haffner\JhCaptcha\Validation\ErrorCheck\ReCaptcha
        config {
            enable = 1
        }
    }
}`
But anyway it uses \Typoheads\Formhandler which is not part of TYPO3 v9

**Comment by schuberttobias** [comment]
@Voronov Thank you for these hints. In the end I figured out the problem(s): spamshield needs to be enabled!

i.e. `plugin.tx_powermail.settings.setup.spamshield._enable = 1` must be set
In my case, it was set to 0 in some Typo3 Template which I overlooked.

After enabling spamshield, submitting the powermail form now only works if the captcha is solved!
