### ISSUE TITLE
Missing Typo3 10.4.x LTS Support

### ISSUE THREAD

**Issue by ProWebs** [TehTux/jh_captcha#20]
Support for 10.4 LTS is not given yet.

The following errors were found while trying to install "jh_captcha":
Your TYPO3 version is higher than this extension requires. It requires TYPO3 versions 8.7.0 - 9.5.99

**Comment by melaniemedialight** [comment]
Hi ! 

We had to use the extension despite its incompatibility with TYPO3 10.

Here are the changes we made (if it may help) :
**ext_tables.php :** 

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
    'jh_captcha',
    'Configuration/TypoScript',
    'Google reCAPTCHA (v2/v3)'
);
```

instead of

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
    $_EXTKEY,
    'Configuration/TypoScript',
    'Google reCAPTCHA (v2/v3)'
);
```
 

**Classes/ViewHelpers/ReCaptchaViewHelper.php**

`class ReCaptchaViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper`

instead of 

`class ReCaptchaViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper`

**Comment by bernd-reindl** [comment]
> Hi !
> 
> We had to use the extension despite its incompatibility with TYPO3 10.
> 
> Here are the changes we made (if it may help) :
> **ext_tables.php :**
> 
> ```
> \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
>     'jh_captcha',
>     'Configuration/TypoScript',
>     'Google reCAPTCHA (v2/v3)'
> );
> ```
> 
> instead of
> 
> ```
> \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
>     $_EXTKEY,
>     'Configuration/TypoScript',
>     'Google reCAPTCHA (v2/v3)'
> );
> ```
> 
> **Classes/ViewHelpers/ReCaptchaViewHelper.php**
> 
> `class ReCaptchaViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper`
> 
> instead of
> 
> `class ReCaptchaViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper`

Works for me. But you have to move \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile() to Configuration/TCA/Overrides/sys_file_references.php, because TCA changes are no longer allowed in ext_tables.php.
![image](https://user-images.githubusercontent.com/2369089/89413942-eabb5d00-d729-11ea-872a-4f14ae5ab70d.png)

**Comment by Moongazer** [comment]
@TehTux Can you create a branch for v10 where we commit these changes? It seems quite easy to make this extension future ready... I'd apprechiate it!

**Comment by aaxc** [comment]
Same here, this is a really nice a simple to use plugin but it is also the last addon on my list that is not TYPO3 v10 ready and I really would not want to make a local fork to make these fixes
