### ISSUE TITLE
Validation is disabled in EXT:form

### ISSUE THREAD

**Issue by plojewski** [TehTux/jh_captcha#31]
Hi there,
when I change v3 secretKey for wrong (invented) and add captcha field to EXT:form, the form is sent anyway.

**Comment by joey-bolts** [comment]
@plojewski 

You are correct, jh_captcha does not work out of the box. Since the field is set to disabled:
https://github.com/TehTux/jh_captcha/blob/114fa8d4054333d9d5374ae49a1c99a4fff5b950/Configuration/Yaml/ReCaptcha/BaseSetup.yaml#L20
It does not trigger validation on form send. You can however fully setup a form with the field in the back-end, it will also render correctly in the front-end. 

I'm not sure why @TehTux included this line. I will provide a PR with the fix.

**Comment by TehTux** [comment]
I mean I would have added it to stop displaying in on the confirmation page and in the emails. Apparently I didn't test the function after that, sorry! 

I have now solved it with Variants. There will be a new version soon.
